- realm: prod
  email: bchen@twilio.com
  twiliojs: //static.twilio.com/libs/twiliojs/1.2/twilio.js
  account_sid: AC665ae3c5061ad161f31137c3f643e81b
  auth_token: d386087bea01cceedb8edf5b87b38f7f
  app_sid: AP45f30a1c7ddae3d6a61f785b5f23385f
  phone: '+16263250398'
  chunder: chunder.twilio.com
  chunderw: chunderw-gll.twilio.com
  matrix: matrix.twilio.com
  client: bchen

- realm: dev
  email: bchen@twilio.com
  twiliojs: //static.dev.twilio.com/libs/twiliojs/1.2/twilio.js
  account_sid: AC17a2da5cff36c1727d063d463cc60729
  auth_token: 0335146d49b13b7621efb459946119bd
  app_sid: AP2733a720d0fac752127315d92e1bc11b
  phone: '+16024289255'
  chunder: chunder.dev.twilio.com
  chunderw: chunderw.dev.twilio.com
  matrix: matrix.dev.twilio.com
  client: bchen

- realm: stage
  email: bchen@twilio.com
  twiliojs: //static.stage.twilio.com/libs/twiliojs/1.2/twilio.js
  account_sid: ACc3b7fb56797dee47e31cd487f8f6da84
  auth_token: 7db11de08e4366bd7e19c58793ee67d2
  app_sid: APdd3c9767a99f13f18f7d3b09fc257ae1
  phone: '+16024286943'
  chunder: chunder.stage.twilio.com
  chunderw: chunderw.stage.twilio.com
  matrix: matrix.stage.twilio.com
  client: bchen
